[package]
name = "tfy-cli"
edition.workspace = true
version.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "tfy"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
clap.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
tfy-core = { path = "../tfy-core" }
tfy-runtime = { path = "../tfy-runtime" }

[dev-dependencies]
sha2.workspace = true
tempfile.workspace = true
